name: Build And Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  RepositoryName: "es-aci-dev"
  #To do, this can be pulled from the Docker Base Image?
  ImageVersion: "7.9.2"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Docker login
      uses: docker/login-action@v1.13.0
      with:
        ecr: false
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}   
             
    - name: Build and push docker image
      uses: docker/build-push-action@v2.9.0
      with:
        file: ./Dockerfile
        tags: ${{ secrets.DOCKER_USER }}/${{env.RepositoryName}}:${{env.ImageVersion}},${{ secrets.DOCKER_USER }}/${{env.RepositoryName}}:latest
        push: ${{ github.ref_name == 'main' }}
